server:
  port: 8088

spring:
  profiles:
    active: local

--- # local 환경
spring:
  profiles: local
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:h2:~/test
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true